import xarray as xr
import numpy as np
from datetime import date
import matplotlib.pyplot as plt
import warnings, os, yaml
import matplotlib
import getpass
import os
import subprocess
import netCDF4
import cartopy.crs as ccrs
import cartopy.feature
import cartopy.feature as cfeature
import matplotlib.pyplot as plt
import numpy.ma as ma
# mom6_tools
from mom6_tools.MOM6grid import MOM6grid
from mom6_tools.m6toolbox import genBasinMasks
from mom6_tools.m6plot import myStats, annotateStats
from mom6_tools.m6plot import xyplot, ztplot
from mom6_tools.m6toolbox import weighted_temporal_mean
from mom6_tools.poleward_heat_transport import heatTrans, plotHeatTrans, plotGandW
import glob

warnings.filterwarnings("ignore")
matplotlib.rcParams.update({'font.size': 12})


def cime_xmlquery(caseroot, varname):
    """run CIME's xmlquery for varname in the directory caseroot, return the value"""
    try:
        value = subprocess.check_output(
            ["./xmlquery", "-N", "--value", varname],
            stderr=subprocess.STDOUT,
            cwd=caseroot,
        )
    except subprocess.CalledProcessError:
        value = subprocess.check_output(
            ["./xmlquery", "--value", varname], stderr=subprocess.STDOUT, cwd=caseroot
        )
    return value.decode()

def count_word_occurrences(data, word):
    count = 0
    if isinstance(data, dict):
        for key, value in data.items():
            count += count_word_occurrences(key, word)
            count += count_word_occurrences(value, word)
    elif isinstance(data, list):
        for item in data:
            count += count_word_occurrences(item, word)
    elif isinstance(data, str):
        count += data.lower().split().count(word.lower())
    return count

# for plotting, the following was a feedback from Keith Lindsay.
linestyle = ['solid','solid','solid',
             'dashed','dashed','dashed',
             'dotted','dotted','dotted']
color = ['black','red','blue','black',
         'red','blue','black',
         'red','blue']
# check with Keith Lindsay
plt.style.use('tableau-colorblind10')

# Get the directory of the current script
script_dir = os.path.dirname(os.path.realpath(__file__))
# Define path to the yaml file 
yml_path = os.path.join(script_dir, '..', 'diag_config.yml')

diag_config_yml = yaml.load(open(yml_path,'r'), Loader=yaml.Loader)

#diag_config_yml = yaml.load(open('../diag_config.yml','r'),
#                            Loader=yaml.Loader)
# initialize lists
casename=[]
label = []; OUTDIR=[]
ocn_path = []; climo_path = []

word_to_search = 'Case'
ncases = count_word_occurrences(diag_config_yml, word_to_search)

#ncases = len(diag_config_yml.keys()) - 1
if ncases < 2:
  # Create the case instance
  caseroot = diag_config_yml['Case']['CASEROOT']
  casename.append(cime_xmlquery(caseroot, 'CASE'))
  label.append(diag_config_yml['Case']['SNAME'])
  ocn_path.append(diag_config_yml['Case']['OCN_DIAG_ROOT'])
  climo_path.append(os.path.join(ocn_path[0], 'climo/'))
  DOUT_S = cime_xmlquery(caseroot, 'DOUT_S')
  if DOUT_S:
    out = cime_xmlquery(caseroot, 'DOUT_S_ROOT')+'/ocn/hist/'
  else:
    out = cime_xmlquery(caseroot, 'RUNDIR')+'/'

  OUTDIR.append(out)

else:
  for i in range(ncases):
    cname = 'Case{}'.format(i+1)
    caseroot = diag_config_yml[cname]['CASEROOT']
    casename.append(cime_xmlquery(caseroot, 'CASE'))
    label.append(diag_config_yml[cname]['SNAME'])
    ocn_path.append(diag_config_yml[cname]['OCN_DIAG_ROOT'])
    climo_path.append(os.path.join(ocn_path[i], 'climo/'))
    DOUT_S = cime_xmlquery(caseroot, 'DOUT_S')
    if DOUT_S:
      out = cime_xmlquery(caseroot, 'DOUT_S_ROOT')+'/ocn/hist/'
    else:
      out = cime_xmlquery(caseroot, 'RUNDIR')+'/'

    OUTDIR.append(out)

print(OUTDIR)
# set avg dates
avg = diag_config_yml['Avg']
start_date = avg['start_date']
end_date = avg['end_date']

print('Casename is {}'.format(casename))
print('─' * 60)
print('Averaged between {} and {}'.format(start_date, end_date))
print('─' * 60)
print('Output directory is:', OUTDIR)
print('─' * 60)
print('Generated by {}'.format(getpass.getuser()))
print('─' * 60)
print("Last update:", date.today())

grd = []
grd_xr = []
depth = []

for i in range(len(casename)):
  geom_file = glob.glob(OUTDIR[i]+'/*.mom6.h.ocean_geometry.nc')[0]
  if not os.path.exists(geom_file):
    geom_file = None

  # load grid and pre-difined masks
  fname = glob.glob(OUTDIR[i]+'*.static.nc')[0]
  grd.append(MOM6grid(fname, geom_file))
  grd_xr.append(MOM6grid(fname, geom_file, xrformat=True))
  try:
    # remote Nan's, otherwise genBasinMasks won't work
    depth_tmp=grd[i].depth_ocean
  except:
    depth_tmp=grd[i].deptho

  depth_tmp[np.isnan(depth_tmp)] = 0.0
  depth.append(depth_tmp)
  print(depth[i].shape)
  print(grd[i])

def compute_basin_code(basin_from_file=None):
  """Returns a list of basin-mask DataArrays (one per case, same order as casename),
  as returned by genBasinMasks(..., xda=True). If basin_from_file is given, it is
  passed through to genBasinMasks for every case instead of computing the masks from
  the grid (see genBasinMasks's basin_from_file argument)."""
  codes = []
  for i in range(len(casename)):
    codes.append(genBasinMasks(grd[i].geolon, grd[i].geolat, depth[i],
                                basin_from_file=basin_from_file))
  return codes

def get_heat_transport_obs():
    """Plots model vs obs poleward heat transport for the global, Pacific and Atlantic basins"""
    # Load Observations
    fObs = netCDF4.Dataset('/glade/work/gmarques/cesm/datasets/Trenberth_and_Caron_Heat_Transport.nc')
    #Trenberth and Caron
    yobs = fObs.variables['ylat'][:]
    NCEP = {}; NCEP['Global'] = fObs.variables['OTn']
    NCEP['Atlantic'] = fObs.variables['ATLn'][:]; NCEP['IndoPac'] = fObs.variables['INDPACn'][:]
    ECMWF = {}; ECMWF['Global'] = fObs.variables['OTe'][:]
    ECMWF['Atlantic'] = fObs.variables['ATLe'][:]; ECMWF['IndoPac'] = fObs.variables['INDPACe'][:]

    #G and W
    Global = {}
    Global['lat'] = np.array([-30., -19., 24., 47.])
    Global['trans'] = np.array([-0.6, -0.8, 1.8, 0.6])
    Global['err'] = np.array([0.3, 0.6, 0.3, 0.1])

    Atlantic = {}
    Atlantic['lat'] = np.array([-45., -30., -19., -11., -4.5, 7.5, 24., 47.])
    Atlantic['trans'] = np.array([0.66, 0.35, 0.77, 0.9, 1., 1.26, 1.27, 0.6])
    Atlantic['err'] = np.array([0.12, 0.15, 0.2, 0.4, 0.55, 0.31, 0.15, 0.09])

    IndoPac = {}
    IndoPac['lat'] = np.array([-30., -18., 24., 47.])
    IndoPac['trans'] = np.array([-0.9, -1.6, 0.52, 0.])
    IndoPac['err'] = np.array([0.3, 0.6, 0.2, 0.05,])

    GandW = {}
    GandW['Global'] = Global
    GandW['Atlantic'] = Atlantic
    GandW['IndoPac'] = IndoPac
    return NCEP, ECMWF, GandW, yobs

NCEP, ECMWF, GandW, yobs = get_heat_transport_obs()

def get_adv_diff(ds):
    # create a ndarray subclass
    class C(np.ndarray): pass

    varName = 'T_ady_2d'
    if varName in ds.variables:
        tmp = np.ma.masked_invalid(ds[varName].values)
        tmp = tmp[:].filled(0.)
        advective = tmp.view(C)
        advective.units = 'W'
    else:
        raise Exception('Could not find "T_ady_2d"')

    varName = 'T_diffy_2d'
    if varName in ds.variables:
        tmp = np.ma.masked_invalid(ds[varName].values)
        tmp = tmp[:].filled(0.)
        diffusive = tmp.view(C)
        diffusive.units = 'W'
    else:
        diffusive = None
        warnings.warn('Diffusive temperature term not found. This will result in an underestimation of the heat transport.')

    varName = 'T_hbd_diffy_2d'
    if varName in ds.variables:
        tmp = np.ma.masked_invalid(ds[varName].values)
        tmp = tmp[:].filled(0.)
        diffusive = diffusive + tmp.view(C)
    else:
        warnings.warn('Horizontal boundary mixing term not found. This will result in an underestimation of the heat transport.')

    return advective, diffusive

def plot_heat_trans(ds, label, linestyle='-'):
    adv, diff = get_adv_diff(ds)
    HT = heatTrans(adv,diff); y = ds.yq
    plt.plot(y, HT, linewidth=3, linestyle=linestyle, label=label)
    return

def heatTrans(advective, diffusive=None, hbd=None, vmask=None, units="W"):
  """Converts vertically integrated temperature advection/diffusion into heat transport"""
  HT = advective[:]
  if diffusive is not None:
    HT = HT + diffusive[:]
  if hbd is not None:
    HT = HT + hbd[:]
  if len(HT.shape) == 3:
    HT = HT.mean(axis=0)
  if units == "Celsius meter3 second-1":
    rho0 = 1.035e3
    Cp = 3992.
    HT = HT * (rho0 * Cp)
    HT = HT * 1.e-15  # convert to PW
  elif units == "W":
    HT = HT * 1.e-15
  else:
    print('Unknown units')
  if vmask is not None: HT = HT*vmask
  HT = HT.sum(axis=-1); HT = HT.squeeze() # sum in x-direction
  return HT

# functions to plot volume transport time series
def plot_transport_time_series(ds, section_name, labels, to_yearly=False, observed_values=None):
    """
    Plot the time series of transport for a given section, with options for yearly aggregation
    and overlaying observed ranges or mean values.

    Parameters:
        ds (xarray.Dataset): Dataset containing the 'transport' variable with
                             dimensions (sections, time).
        section_name (str): Name of the section to plot.
        to_yearly (bool): If True, aggregates the time series to yearly means.
        observed_values (tuple or float, optional): Observed range (min, max) or mean value
                                                    to overlay on the plot.
    """
    plt.figure(figsize=(10, 6))
    for i in range(len(labels)):
        
        # Check if the section exists
        if ('h.'+section_name) not in ds[i].sections.values:
            print(f"Section '{section_name}' not found in the '{labels[i]}' dataset. Skipping plot.")
            return
    
        # Check for required dimensions and variables
        if "sections" not in ds[i].dims or "time" not in ds[i].dims:
            raise ValueError("Dataset must contain 'sections' and 'time' dimensions.")
        if "transport" not in ds[i].data_vars:
            raise ValueError("Dataset must contain 'transport' as a data variable.")
    
        section_data = ds[i].sel(sections='h.'+section_name)
        transport = section_data["transport"]
        # Convert to yearly time series if requested
        if to_yearly:
            section_data = weighted_temporal_mean(section_data,'transport')
            transport = section_data
            
        # Plot the time series
        plt.plot(section_data["time"], transport, label=f"Case: {labels[i]}", lw=2)
        
    plt.xlabel("Time")
    plt.ylabel("Transport (Sv)")
    plt.title(f"Volume Transport Across {section_name}")
    plt.grid()
    plt.legend()
     # Overlay observed range or mean
    if observed_values is not None:
        if isinstance(observed_values, (tuple, list)) and len(observed_values) == 2:
            plt.axhspan(
                observed_values[0], observed_values[1], color="gray", alpha=0.2,
                label=f"Observed Range: {observed_values[0]} to {observed_values[1]}"
            )
        elif isinstance(observed_values, (int, float)):
            plt.axhline(
                observed_values, color="red", linestyle="--", label=f"Observed Mean: {observed_values}"
            )
        else:
            raise ValueError("Observed values must be a tuple (min, max) or a single numeric mean.")

       
    return

def get_transport_range_or_mean(config_value):
    """
    Given a transport section from diag_config_yml, return either (min, max) or mean,
    handling the case of 'None' as a special case.
    
    Args:
    config_value: list, the transport configuration (e.g., ['umo', 2.0, 3.0] or ['umo', 'None'])
    
    Returns:
    Tuple or mean value, depending on the configuration.
    """
    if 'None' in config_value:  # Check if 'None' is in the list
        return None  # Return None or any other default you'd like for this case
    elif len(config_value) == 2:
        try:
            return float(config_value[1])  # If there's one value, return it as the mean
        except ValueError:
            raise ValueError(f"Invalid value in config: {config_value[1]} cannot be converted to float.")
    elif len(config_value) == 3:
        try:
            return (float(config_value[1]), float(config_value[2]))  # Min, Max case
        except ValueError:
            raise ValueError(f"Invalid values in config: {config_value[1]} or {config_value[2]} cannot be converted to float.")
    else:
        raise ValueError("Invalid configuration format")

	
# functions to plot MLD and BLD

def add_labels(ax, nh='JFM', sh='JAS'):
    bbox_props = dict(boxstyle="round", fc="w", ec="0.5", alpha=0.9)
    ax.plot([grd[0].geolon[0,0], grd[0].geolon[0,-1]], [0,0], 'w--', lw=0.5, transform=ccrs.PlateCarree())
    ax.text(25, 10, nh, ha="center", va="center", size=12, bbox=bbox_props, transform=ccrs.PlateCarree())
    ax.text(25, -10, sh, ha="center", va="center", size=12, bbox=bbox_props, transform=ccrs.PlateCarree())

def plot_map(da, area, grd, label, vmin=None, vmax=None, suptitle='',
             nh='JFM', sh='JAS', cmap='coolwarm'):

  sMin, sMax, sMean, sStd, sRMS = myStats(np.ma.masked_invalid(da), area)
  try:
    cmap_masked = getattr(plt.cm, cmap).copy()
    cmap_masked.set_bad(color='gray')
  except AttributeError:
    print(f"Colormap '{cmap}' not found. Using default 'viridis'.")
    cmap_masked = plt.cm.viridis.copy()
    cmap_masked.set_bad(color='gray')

  fig = plt.figure(figsize=(10, 5))
  ax = fig.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())
  # Add land feature to color continents
  ax.add_feature(cfeature.LAND, facecolor='lightgray')
  plt.suptitle(suptitle)
  pc = ax.pcolormesh(grd.geolon_c, grd.geolat_c, da,
                transform=ccrs.PlateCarree(),vmin=vmin, vmax=vmax,
                cmap=cmap)

  #ax.set_title(label + ', '+ da.description)
  ax.set_title(label)
  annotateStats(ax, sMin, sMax, sMean, sStd, sRMS)
  add_labels(ax, nh=nh, sh=sh)
  cax = fig.add_axes([0.91, 0.22, 0.02, 0.45])
  cbar = plt.colorbar(pc, cax=cax, label='[m]')
  cbar.ax.tick_params(labelsize=12)
  ax.set_global()
  ax.stock_img()
  ax.coastlines()
  # Add gridlines for latitude and longitude
  gl = ax.gridlines(draw_labels=True, linewidth=0.5, color='black', alpha=0.0, linestyle='--')
  # Customize gridline labels
  gl.top_labels = False    # Turn off labels at the top
  gl.right_labels = False  # Turn off labels on the right
  gl.xlabel_style = {'size': 10, 'color': 'black'}
  gl.ylabel_style = {'size': 10, 'color': 'black'};

  return

# functions to plot ENSO

def plot_enso(ds,label):
    fig = plt.figure(figsize=(12, 6))

    plt.fill_between(
    ds.time.values,
    ds.tos.where(
    ds.tos >= 0.4
    ).data,
    0.4,
    color='red',
    alpha=0.9,
    )
    plt.fill_between(
    ds.time.values,
    ds.tos.where(
    ds.tos <= -0.4
    ).data,
    -0.4,
    color='blue',
    alpha=0.9,
    )
    plt.plot(ds.time.values, ds.tos.values, color='black')
    plt.axhline(0, color='black', lw=0.5)
    plt.axhline(0.4, color='black', linewidth=0.5, linestyle='dotted')
    plt.axhline(-0.4, color='black', linewidth=0.5, linestyle='dotted')
    plt.title('Case {}, Niño 3.4 Index'.format(label));
    return

